### ISSUE TITLE
It doesn't do anything

### ISSUE THREAD

**Issue by Ma5t3rful** [seanbreckenridge/tts#1]
typed this in terminal
```sh
$ echo "hello mr streamer" | ./tts.sh 
Reading text from STDIN...
parse error: Invalid numeric literal at line 1, column 10
API Error: 

```

And this was the response. Maybe streamlabs has changed its api. IDK.

**Comment by seanbreckenridge** [comment]
Yeah, looks like they've changed their API

![image](https://github.com/seanbreckenridge/tts/assets/7804791/495fc9a2-3395-4815-8a66-2674b0d9ad87)

This was always using an undocumented API, so not surprised it finally broke

thanks for the comment, will update the readme

**Comment by purarue** [comment]
Yeah, looks like they've changed their API

![image](https://github.com/seanbreckenridge/tts/assets/7804791/630ca46b-ba45-4eb6-83be-d6c57195f902)

This was always using an undocumented API, so not surprised it finally broke

thanks for the comment, will update the readme
